travis:
  secure:
    BINSTAR_TOKEN: GkDSPXjfYMqn9yyGFmpqTf8yh2G53XtFFVIrxoqlwSFAQt3SyeJ6R6y0jmK+RdkcpP+L6dj/3KBYSUu1UQAPcnDBVVW6bEqLm7Pv3WGLfAuFbuCfhxOABlRhgHgZ2rClkM4KGW0v/HoJhVkUFW/6WSJFY1cJzeDNsYwJx/jxRRGzGh0lSVwf7Hp2/qCb1P1AbEL5mQ5zK2igb8D0TmBlSioR8lucnStPQoeGlBDUhI7Q8zOHe6h2UNHtNRYpIFqdYneEzHg5xcYwoT/RxATMOs9aPAdRxnMNKQF9LZYFl5q1qjNFRG1tBXBDHHw3NuQN7GwcXBI1YTTfbB23QAhp/Z2K9pf2XXCNv7+AtxP9tPrcQict4tDyeTc5WaLzi4QcVXYfqKgwrfCI2mNzFTsATHduN8XlSZIFJ2ZunRd6R5nmoVzsS0JoRgiMq2JNXE1SH5KF4NbV3XUql330V9n1FrceKRbAOs7SqfxqhJYXRqt7NMrwK2xU4jcahibX7MgXcdc3jfAJ9xEV3Mnz3kBDps30NwZZM0WuwnO5W+afcb5c2MV474d6XlthEPQLyjcOTlmgKicf6o6Sm6LnOAj4Z0ibocwh5nbKgXDISWv3CzxhNvzY2fMl29UrrO/3QIkV+r1XqM5MlSUDcOzlEMEr2DdEsbptmfMB/jIGMkB9tFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
